print("hello")
print("hey wassup")
print("how are you")
print("i am fine")
print("what about you")
print("i am also fine")
print("what are you doing")
print("i am doing nothing")
print("what about you")
